import { NextRequest, NextResponse } from "next/server";
import { pgDb } from "@/lib/db/postgres";
import { createSignedAudioUrl } from "@/lib/supabase/storage";
import { verifyLaunchToken } from "@/lib/auth/launch-token";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ attemptId: string }> },
) {
  const { attemptId } = await params;
  const token = req.nextUrl.searchParams.get("token");

  // 1. Enforce strict token requirement: No token = No access!
  if (!token) {
    return NextResponse.json(
      {
        success: false,
        error:
          "Access token required. You can only access this detailed report using the secure link generated by the bot via *result/*ketqua on Mezon.",
      },
      { status: 403 },
    );
  }

  // 2. Validate cryptographic signature and expiration of the launch token
  const payload = verifyLaunchToken(token);
  if (!payload || payload.attemptId !== attemptId) {
    return NextResponse.json(
      {
        success: false,
        error:
          "Invalid or expired access token. Please run *result (or *ketqua) on Mezon to generate a new link (valid for 24 hours).",
      },
      { status: 403 },
    );
  }

  try {
    const attempt = await pgDb.getIELTSAttempt(attemptId);
    if (!attempt) {
      return NextResponse.json(
        { success: false, error: "IELTS Speaking test attempt not found." },
        { status: 404 },
      );
    }

    // Verify that attempt belongs to the user specified in the signed token
    if (
      attempt.user_id !== payload.userId &&
      attempt.user_id !== payload.mezonId
    ) {
      return NextResponse.json(
        {
          success: false,
          error: "This test attempt does not belong to the authenticated account.",
        },
        { status: 403 },
      );
    }

    const topic = await pgDb.getIELTSTopic(attempt.topic_id);
    if (!topic) {
      return NextResponse.json(
        { success: false, error: "Test topic not found." },
        { status: 404 },
      );
    }

    if (!attempt.score_result) {
      return NextResponse.json(
        {
          success: false,
          error: "Detailed AI evaluation is not yet available for this test attempt.",
        },
        { status: 400 },
      );
    }

    // Generate signed audio URLs for candidate recordings
    for (const response of Object.values(attempt.responses || {})) {
      if (response.audio_storage_path) {
        try {
          response.audio_url = await createSignedAudioUrl(
            response.audio_storage_path,
          );
        } catch (error) {
          console.error(
            "[GET /api/ielts/[attemptId]/details] Signed audio URL error:",
            error,
          );
          response.audio_url = undefined;
        }
      }
    }

    return NextResponse.json({
      success: true,
      attempt: { ...attempt, unlocked: true },
      topic,
      result: {
        ...attempt.score_result,
        responses: attempt.responses,
        unlocked: true,
      },
    });
  } catch (error) {
    console.error("[GET /api/ielts/[attemptId]/details] Error:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Internal server error loading IELTS Speaking test details.",
      },
      { status: 500 },
    );
  }
}
